phpapache:
    build: .
    dockerfile: Dockerfile_php
    ports:
        - "8080:80"
    volumes:
        - dev:/var/www
    links:
        - db
    container_name: php
    environment:
      VIRTUAL_HOST: php.docker
db:
    build: .
    dockerfile: Dockerfile_mysql
    volumes:
        - mysql:/usr/local/mysql/data
    ports:
        - "3307:3306"
    container_name: mysql
