
version: '3.8'

services:
  app:
    build: ./docker/php/
    container_name: my-project-php
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    image: nginx:1.23.1-alpine
    container_name: my-project-nginx
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
  db:
    image: mysql:8.0.30
    container_name: my-project-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: my-project-db
    volumes:
      - db:/var/lib/mysql
  adminer:
    image: adminer:latest
    container_name: my-project-adminer
    ports:
      - 8080:8080
volumes:
  db: